export interface CardItemInterface {
  icon: ResourceStr;
  name: ResourceStr;
  authorType: ResourceStr;
  content: string;
}
//
// export const CARD_LIST: CardItemInterface[] = [
//   {
//     icon: $r('app.media.ic_icon_1'),
//     name: $r('app.string.name_1'),
//     authorType: $r('app.string.author_type_1'),
//     content: $r('app.string.content_1')
//   },
//   {
//     icon: $r('app.media.ic_icon_2'),
//     name: $r('app.string.name_2'),
//     authorType: $r('app.string.author_type_1'),
//     content: $r('app.string.content_2')
//   },
//   {
//     icon: $r('app.media.ic_icon_2'),
//     name: $r('app.string.name_2'),
//     authorType: $r('app.string.author_type_1'),
//     content: $r('app.string.content_3')
//   },
//   {
//     icon: $r('app.media.ic_icon_3'),
//     name: $r('app.string.name_3'),
//     authorType: $r('app.string.author_type_2'),
//     content: $r('app.string.content_4')
//   },
//   {
//     icon: $r('app.media.ic_icon_4'),
//     name: $r('app.string.name_4'),
//     authorType: $r('app.string.author_type_3'),
//     content: $r('app.string.content_5')
//   },
//   {
//     icon: $r('app.media.ic_icon_2'),
//     name: $r('app.string.name_5'),
//     authorType: $r('app.string.author_type_4'),
//     content: $r('app.string.content_6')
//   },
//   {
//     icon: $r('app.media.ic_icon_1'),
//     name: $r('app.string.name_1'),
//     authorType: $r('app.string.author_type_1'),
//     content: $r('app.string.content_1')
//   },
//   {
//     icon: $r('app.media.ic_icon_2'),
//     name: $r('app.string.name_2'),
//     authorType: $r('app.string.author_type_1'),
//     content: $r('app.string.content_2')
//   },
//   {
//     icon: $r('app.media.ic_icon_3'),
//     name: $r('app.string.name_3'),
//     authorType: $r('app.string.author_type_2'),
//     content: $r('app.string.content_4')
//   },
//   {
//     icon: $r('app.media.ic_icon_4'),
//     name: $r('app.string.name_4'),
//     authorType: $r('app.string.author_type_3'),
//     content: $r('app.string.content_5')
//   },
//   {
//     icon: $r('app.media.ic_icon_2'),
//     name: $r('app.string.name_5'),
//     authorType: $r('app.string.author_type_4'),
//     content: $r('app.string.content_6')
//   }
// ]