import { PictureItem } from '../../viewmodel/PictureItem';

/**
 * Pictures of banner.
 */
export const PICTURE_BANNER: PictureItem[] = [
  { id: '1', name: '', description: '怒海波涛', image: $r('app.media.index1') },
  { id: '2', name: '', description: '大山深处感人的亲情之歌', image: $r('app.media.index2') },
  { id: '3', name: '', description: '荒漠的亲情之歌', image: $r('app.media.index3') }
];

export const PICTURE_MAP: Map<string, Resource> = new Map([
  ['story1.jpg', $r('app.media.story1')],
  ['story2.jpg', $r('app.media.story2')],
  ['story3.jpg', $r('app.media.story3')],
  ['story4.jpg', $r('app.media.story4')],
  ['story5.jpg', $r('app.media.story5')],
  ['story6.jpg', $r('app.media.story6')],
  ['story7.jpg', $r('app.media.story7')],
  ['story8.jpg', $r('app.media.story8')],
  ['story9.jpg', $r('app.media.story9')],
  ['story10.jpg', $r('app.media.story10')],
  ['story11.jpg', $r('app.media.story11')],
  ['story12.jpg', $r('app.media.story12')],
  ['story13.jpg', $r('app.media.story13')],
  ['story14.jpg', $r('app.media.story14')],
  ['story15.jpg', $r('app.media.story15')],
  ['tip1.jpg', $r('app.media.tip1')],
  ['tip2.jpg', $r('app.media.tip2')],
  ['tip3.jpg', $r('app.media.tip3')],
  ['tip4.jpg', $r('app.media.tip4')],
  ['tip5.jpg', $r('app.media.tip5')],
  ['tip6.jpg', $r('app.media.tip6')],
  ['tip7.jpg', $r('app.media.tip7')],
  ['tip8.jpg', $r('app.media.tip8')],
  ['tip9.jpg', $r('app.media.tip9')],
  ['tip10.jpg', $r('app.media.tip10')],
  ['tip11.jpg', $r('app.media.tip11')],
  ['tip12.jpg', $r('app.media.tip12')],
  ['tip13.jpg', $r('app.media.tip13')],
  ['tip14.jpg', $r('app.media.tip14')],
  ['tip15.jpg', $r('app.media.tip15')],
  ['meeting1.jpg', $r('app.media.meeting1')],
  ['meeting2.jpg', $r('app.media.meeting2')],
  ['interview1.jpg', $r('app.media.interview1')],
  ['meeting3.jpg', $r('app.media.meeting3')],
  ['interview2.jpg', $r('app.media.interview2')],
  ['meeting1.jpg', $r('app.media.meeting1')],
  ['interview3.jpg', $r('app.media.interview3')],
  ['meeting2.jpg', $r('app.media.meeting2')],
  ['restaurant1.jpg', $r('app.media.restaurant1')],
  ['coffee1.jpg', $r('app.media.coffee1')],
  ['coffee2.jpg', $r('app.media.coffee2')],
  ['restaurant2.jpg', $r('app.media.restaurant2')],
  ['restaurant3.jpg', $r('app.media.restaurant3')],
  ['restaurant1.jpg', $r('app.media.restaurant1')],
  ['bus1.jpg', $r('app.media.bus1')],
  ['airport1.jpg', $r('app.media.airport1')],
  ['bus2.jpg', $r('app.media.bus2')],
  ['bus3.jpg', $r('app.media.bus3')],
  ['airport2.jpg', $r('app.media.airport2')],
  ['elevator1.jpg', $r('app.media.elevator1')],
  ['queue1.jpg', $r('app.media.queue1')],
  ['library1.jpg', $r('app.media.library1')],
  ['cinema1.jpg', $r('app.media.cinema1')],
  ['queue2.jpg', $r('app.media.queue2')],
  ['supermarket1.jpg', $r('app.media.supermarket1')],
  ['gym1.jpg', $r('app.media.gym1')],
  ['supermarket2.jpg', $r('app.media.supermarket2')],
  ['hospital1.jpg', $r('app.media.hospital1')],
  ['supermarket3.jpg', $r('app.media.supermarket3')],
  ['supermarket4.jpg', $r('app.media.supermarket4')],
  ['cinema2.jpg', $r('app.media.cinema2')],
  ['supermarket5.jpg', $r('app.media.supermarket5')],
  ['gym2.jpg', $r('app.media.gym2')],
  ['park1.jpg', $r('app.media.park1')],
  ['party1.jpg', $r('app.media.party1')],
  ['cinema1.jpg', $r('app.media.cinema1')],
  ['park2.jpg', $r('app.media.park2')],
  ['gym1.jpg', $r('app.media.gym1')]

])

// /**
//  * pictures of recently play.
//  */
// export const PICTURE_RECENTLY: PictureItem[] = [
//   { id: '1', name: '背影', description: '感人的亲情之歌', image: $r('app.media.recently1') },
//   { id: '2', name: '废墟之上', description: '勇闯无人之境', image: $r('app.media.recently2') },
//   { id: '3', name: '无根之人', description: '悬疑国产力作', image: $r('app.media.recently3') },
//   { id: '4', name: '摩天轮', description: '每个人心中都有一个童话', image: $r('app.media.recently4') }
// ];
//
// /**
//  * pictures of photo.
//  */
// export const PICTURE_PHOTO: PictureItem[] = [
//   { id: '1', name: '蓝·静', description: '用放大镜看世界', image: $r('app.media.photo1') },
//   { id: '2', name: '花', description: '每个人心中都有一个童话', image: $r('app.media.photo2') },
//   { id: '3', name: '无根之人', description: '悬疑国产力作', image: $r('app.media.recently3') },
//   { id: '4', name: '摩天轮', description: '每个人心中都有一个童话', image: $r('app.media.recently4') }
// ];

/**
 * pictures of newest.
 */
export const PICTURE_LATEST: PictureItem[] = [
  { id: '1', name: '潮·设计大会', description: '国际设计大师分...', image: $r('app.media.movie1') },
  { id: '2', name: '食客', description: '味蕾爆炸', image: $r('app.media.movie2') },
  { id: '3', name: '绿野仙踪', description: '热带雨林的故事', image: $r('app.media.image3') },
  { id: '4', name: '塔', description: '2021最期待的电...', image: $r('app.media.movie4') },
  { id: '5', name: '微缩世界', description: '用放大镜看世界', image: $r('app.media.movie5') },
  { id: '6', name: '非常规接触', description: '少年的奇妙之旅', image: $r('app.media.movie6') },
  { id: '7', name: '绿野仙踪', description: '热带雨林的故事', image: $r('app.media.movie7') },
  { id: '8', name: '塔', description: '用放大镜看世界', image: $r('app.media.movie8') },
  { id: '9', name: '食客', description: '热带雨林的故事', image: $r('app.media.movie9') }
];

/**
 * type of pictures.
 */
export enum PictureType {
  QUESTION = 'question',
  TIP = 'tip',
  STORY = 'story',
  // RECENTLY = 'recently',
  // PHOTO = 'photo',
  LATEST = 'latest',
  BANNER = 'banner'
}