export class TestScore {
  /**
   * News image list item id.
   */
  id: number | null = null;

  /**
   * User ID.
   */
  userId: string | null = null;

  /**
   * Test ID.
   */
  testId: string | null = null;

  /**
   * Score.
   */
  score: number | null = null;

  /**
   * Creation time.
   */
  createTime: Date | null = null;

  /**
   * Deletion time.
   */
  deleteTime: Date | null = null;
}